name: VocaListener-Modern
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.14
  - numpy=2.3.5
  - librosa=0.11.0
  - pysoundfile
  - tqdm=4.67.1
  - conda-forge::montreal-forced-aligner=3.3.8
  - conda-forge::kalpy=0.8.2=*cpu*
  - conda-forge::openfst=1.8.4
  - conda-forge::ffmpeg=8.0.1=gpl_*
  - conda-forge::sox=14.4.2
  - conda-forge::pyqt
  - setuptools<81.0.0
  - pip
  - pip:
    - pyqt6-tools
